### ISSUE TITLE
>Pandarus

### ISSUE THREAD

**Issue by kakhulu31** [PandarusAnon/slaude#1]
I don't get it, Please explain the meaning. Is it just russian panda or something else?

**Comment by PandarusAnon** [comment]
https://en.wikipedia.org/wiki/Pandarus
>The plot function of the aging lecher Pandarus in Chaucer's and Shakespeare's famous works has given rise to the English terms a pander (in later usage a panderer), from Chaucer, meaning a person who furthers other people's illicit sexual amours

**Comment by kakhulu31** [comment]
Ok, that makes much more sense than panda, thanks.
